get_k3s_url: https://get.k3s.io
k3s_version: v1.17.3+k3s1
kube_dashboard_version: v2.0.0-rc5
nginx_image: nginx:stable-alpine
temp_dir: /tmp/k8s_pi
storage_devide: /dev/sda
storage_mount: /mnt/ssd
nfs_mount: /mnt/nfs
nginx_config_dir: /etc/nginx
htpasswd_dir: /etc/apache2/.htpasswd
lets_encrypt_dir: /etc/letsencrypt
k8s_home: /home/k8s
nodejs_version: 12.x
dhparam_size: 256
certbot_email: siyuangao@gmail.com
certbot_staging: true
cert_domains:
  - "*.elica.io"
