---
- name: check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: kill all k3s resources
  shell: /usr/local/bin/k3s-killall.sh
  when: k3s_installed.stat.exists == true

- name: uninstall k3s
  shell: /usr/local/bin/k3s-agent-uninstall.sh
  when: k3s_installed.stat.exists == true

- name: Unmount nfs share
  become: yes
  mount:
    path: "{{ nfs_mount }}"
    src: "{{ hostvars[groups['kube-master'][0]].ansible_default_ipv4.address }}:{{ storage_mount }}"
    fstype: nfs
    state: absent
