---
image:
  repository: {{ unifi_image.split(":")[0] }}
  tag: "{{ unifi_image.split(":")[1] }}"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/tls-acme: "true"
  hosts:
    - unifi.{{ ingress_domain }}
  tls:
    - hosts:
      - unifi.{{ ingress_domain }}
      secretName: unifi-cert
controllerService:
  externalIPs:
    - {{ansible_default_ipv4.address}}
  port: 8080
stunService:
  externalIPs:
    - {{ansible_default_ipv4.address}}
  port: 3478
discoveryService:
  externalIPs:
    - {{ansible_default_ipv4.address}}
  port: 10001
persistence:
  enabled: true
  storageClass: gluster-heketi
  accessModes: ReadWriteOnce
  size: "{{ unifi_storage_size }}"
podAnnotations:
  backup.ark.heptio.com/backup-volumes: unifi-data
