---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  app.kubernetes.io/name: {{ include "dns-updater.name" . }}
  helm.sh/chart: {{ include "dns-updater.chart" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
