---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  app.kubernetes.io/name: {{ include "dns-updater.name" . }}
  helm.sh/chart: {{ include "dns-updater.chart" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  email: "{{ .Values.cloudflare.email | b64enc }}"
  api_token: "{{ .Values.cloudflare.api_token | b64enc }}"
