---
- name: copy role files
  copy:
    src: ./
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install helm cli
  become: yes
  become_user: root
  unarchive:
    src: https://get.helm.sh/helm-{{ helm_version }}-beta.4-linux-{{ helm_arch }}.tar.gz
    extra_opts:
      - "--strip-components=1"
      - "linux-{{ helm_arch }}/helm"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes

- name: add helm chart repo
  shell: >
    helm repo add stable https://kubernetes-charts.storage.googleapis.com/

- name: add jetstack chart
  shell: >
    helm repo add jetstack https://charts.jetstack.io

- name: update helm chart
  shell: >
    helm repo update
