---
- name: check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: kill all k3s resources
  shell: /usr/local/bin/k3s-killall.sh
  when: k3s_installed.stat.exists == true

- name: uninstall k3s
  shell: /usr/local/bin/k3s-uninstall.sh
  when: k3s_installed.stat.exists == true

- name: remove etcd directory
  become: yes
  file:
    path: /var/lib/etcd
    state: absent

- name: remove dns-updater directory
  become: yes
  file:
    path: /home/k8s/dns-updater
    state: absent

- name: remove dns-updater configuration
  become: yes
  file:
    path: /home/k8s/.cloudflare-ddns
    state: absent

- name: remove dns-updater cron job
  cron:
    name: dns-updater
    state: absent
