---
- name: Check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Kill all k3s resources
  shell: /usr/local/bin/k3s-killall.sh
  when: k3s_installed.stat.exists == true

- name: Uninstall k3s
  shell: /usr/local/bin/k3s-uninstall.sh
  when: k3s_installed.stat.exists == true

- name: Remove temp files directory
  become: yes
  file:
    path: "{{ temp_dir }}"
    state: absent

- name: Create temp directory
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Remove nfs exports
  become: yes
  file:
    path: /etc/exports
    state: absent

- name: Remove nfs-kernel-server package
  become: yes
  apt:
    name: nfs-kernel-server
    state: absent

- name: Reset mount
  become: yes
  mount:
    path: "{{ storage_mount }}"
    src: "{{ storage_devide }}"
    fstype: ext4
    state: unmounted
