---
- name: check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: kill all k3s resources
  shell: /usr/local/bin/k3s-killall.sh
  when: k3s_installed.stat.exists == true

- name: uninstall k3s
  shell: /usr/local/bin/k3s-uninstall.sh
  when: k3s_installed.stat.exists == true

- name: remove temp files directory
  become: yes
  file:
    path: "{{ temp_dir }}"
    state: absent

- name: create temp directory
  file:
    path: "{{ temp_dir }}"
    state: directory
