---
image:
  repository: {{ ark_image.split(":")[0] }}
  tag: "{{ ark_image.split(":")[1] }}"
configuration:
  restoreOnlyMode: {{ backup_restore_only_mode }}
  backupStorageProvider:
    name: {{ backup_provider }}
    bucket: {{ backup_bucket }}
    resticLocation: {{ backup_volumes_bucket }}
credentials:
  secretContents:
    {{ backup_provider}}: |
      {{ backup_credentials | indent(width=6) }}
