apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    kubernetes.io/ingress.class: "{{ ingress_class }}"
    cert-manager.io/cluster-issuer: "{{ ingress_issuer }}"
  name: {{ item.name }}-ingress
  namespace: external-services
spec:
  rules:
  - host: {{ item.ingress_domain }}
    http:
      paths:
      - backend:
          serviceName: external-{{ item.name }}-http
          servicePort: {{ item.service_port }}
        path: /
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - {{ item.ingress_domain }}
    secretName: {{ item.ingress_domain }}-tls # < cert-manager will store the created certificate in this secret.
