---
- name: Copy over helm deploy file
  template:
    src: metallb-helm.yaml
    dest: "{{ temp_dir }}/metallb-helm.yaml"

- name: Install metallb from helm
  k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ temp_dir }}/metallb-helm.yaml"
