- name: clone dns-updater
  git:
    repo: https://github.com/r1cebank/cloudflare-ddns-client.git
    dest: "{{ k8s_home }}/dns-updater"

- name: install dns-updater
  shell: make install
  args:
    chdir: /home/k8s/dns-updater

- name: copy dns-updater configuration
  template:
    src: cloudflare-ddns
    dest: "{{ k8s_home }}/.cloudflare-ddns"

- name: create dns-updater cron job
  cron:
    minute="0"
    hour="0"
    name="dns-updater"
    job="/usr/local/bin/cloudflare-ddns --update-now > /dev/null 2>&1"
