apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: gitea
spec:
  chart: gitea
  repo: {{ personal_chart_url }}
  set:
    app.theme: "arc-green"
    images.gitea: "{{ gitea_image }}"
    ingress.tls: "true"
    service.ssh.serviceType: LoadBalancer
    service.ssh.loadBalancerIP: "{{ gitea_ssh_loadbalancer_ip }}"
    service.http.externalHost: "{{ gitea_ingress_domain }}"
    service.ssh.externalHost: "{{ gitea_ingress_domain }}"
    config.openidSignin: "false"
    persistence.enabled: "true"
    persistence.giteaSize: "100Gi"
    persistence.storageClass: "nfs-client"
    config.requireSignin: "true"
    config.disableRegistration: "true"
  valuesContent: |-
    app:
      title: "Hachune-CX: Git for all"
