apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: gitea
spec:
  chart: gitea
  repo: {{ gitea_chart_url }}
  set:
    images.gitea: "{{ gitea_image }}"
    service.http.externalHost: "{{ gitea_ingress_domain }}"
    service.ssh.externalHost: "{{ gitea_ingress_domain }}"
    config.openidSignin: "false"
    persistence.enabled: "true"
    persistence.giteaSize: "100Gi"
    persistence.storageClass: "nfs-client"
