---
- name: pull updated etcd image
  shell: docker pull {{ etcd_image }}
  args:
    warn: no

- name: remove existing docker container
  shell: docker rm -f etcd
  ignore_errors: true

- name: start new etcd container
  shell: >
    docker run -d --env GOMAXPROCS=4
    -v /var/lib/etcd:/var/lib/etcd
    -p 2379:2379
    -p 2380:2380
    --name=etcd
    --restart=always
    -e ETCD_UNSUPPORTED_ARCH=arm
    {{ etcd_image }}
    etcd
    --name etcd
    --data-dir /var/lib/etcd
    --listen-client-urls http://0.0.0.0:2379
    --advertise-client-urls http://0.0.0.0:2379
    --listen-peer-urls http://localhost:2380
    --initial-advertise-peer-urls http://localhost:2380
    --initial-cluster etcd=http://localhost:2380
    --initial-cluster-token {{ etcd_token }}
    --initial-cluster-state new
