---
- name: copy dns-updater chart
  copy:
    src: ../../../dns-updater
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: template dns-updater config file
  template:
    src: ./dns-updater-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install dns-updater
  shell: >
    helm upgrade
    --install
    --namespace kube-system
    --values /tmp/dns-updater-values.yml
    dns-updater
    /tmp/dns-updater

- name: template cert-manager config
  template:
    src: ./cert-manager-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: create cert-manager namespace
  k8s:
    name: cert-manager
    kind: Namespace
    state: present

- name: apply custom resources
  shell: >
    kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml


- name: install cert-manager
  shell: >
    helm install
    cert-manager
    --version {{ cert_manager_version }}
    jetstack/cert-manager
    --values /tmp/cert-manager-values.yml
    --namespace cert-manager

- name: template cluster-issuer config
  template:
    src: ./cluster-issuer.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: create ClusterIssuer
  k8s:
    src: /tmp/cluster-issuer.yml

- name: template default-cert config
  template:
    src: ./default-cert.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: create default cert
  k8s:
    src: /tmp/default-cert.yml

- name: template nginx config file
  template:
    src: ./nginx-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install nginx
  shell: >
    helm upgrade
    --install
    --namespace kube-system
    --values /tmp/nginx-values.yml
    nginx-ingress
    stable/nginx-ingress
