apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  set:
    loadBalancerIP: "{{ ingress_loadbalancer_ip }}"
    rbac.enabled: "true"
    ssl.enabled: "true"
    sniStrict: "true"
    ssl.enforced: "{{ traefik_force_ssl }}"
    ssl.permanentRedirect: "true"
    ssl.tlsMinVersion: "{{ traefik_tls_min_version }}"
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    dashboard.enabled: "{{ traefik_dashboard_enabled }}"
  valuesContent: |-
    ssl:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
