---
- name: Install nfs-common
  become: yes
  apt:
    name: nfs-common
    state: present

- name: Mount nfs share
  become: yes
  mount:
    path: "{{ nfs_mount }}"
    src: "{{ hostvars[groups['kube-master'][0]].ansible_default_ipv4.address }}:{{ storage_mount }}"
    fstype: nfs
    state: mounted

- name: Set permission on mount
  become: yes
  file:
    path: "{{ nfs_mount }}"
    state: directory
    owner: k8s
    group: k8s
