---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    server: "{{ letsencrypt_server }}"
    email: "{{ letsencrypt_email }}"
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: cf-dns
          cloudflare:
            email: "{{ cloudflare_email }}"
            apiKeySecretRef:
              name: dns-updater-secret
              key: api_token
