---
- name: Test connection
  ping:

- name: Update apt
  become: yes
  become_user: root
  apt:
    update_cache: yes

- name: Install tool packages
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nano
      - build-essential
      - python3-pip
      - python-dev

- name: Switch iptables to legacy mode
  become: yes
  ignore_errors: yes
  become_user: root
  command: "{{ item }}"
  with_items:
    - update-alternatives --set iptables /usr/sbin/iptables-legacy
