---
- name: test connection
  ping:

- name: Update system
  become: yes
  become_user: root
  apt:
    cache_valid_time: 3600
    update_cache: yes
    upgrade: safe

- name: Install tool packages
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nano
      - git
      - make
