---
- name: test connection
  ping:
- name: add apt gpg key
  become: yes
  become_user: root
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: add apt repo
  become: yes
  become_user: root
  apt_repository:
    repo: deb http://apt.kubernetes.io kubernetes-xenial main
- name: run apt update
  become: yes
  become_user: root
  apt:
    update_cache: yes
- name: install kubeadm
  become: yes
  become_user: root
  apt:
    name: kubeadm
    state: latest
