---
- name: Copy over helm deploy file
  template:
    src: cert-manager-helm.yaml
    dest: "{{ temp_dir }}/cert-manager-helm.yaml"

- name: Install cert-manager crds
  shell: "kubectl apply --validate=false -f {{ cert_manager_crds_url }}"

- name: Install cert-manager from helm
  k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ temp_dir }}/cert-manager-helm.yaml"

- name: Copy over clusterIssuer riles
  template:
    src: "{{ item }}"
    dest: "{{ temp_dir }}/{{ item }}"
  with_items:
    - letsencrypt-prod-clusterissuer.yaml
    - letsencrypt-staging-clusterissuer.yaml

- name: Creating clusterIssuer
  k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ temp_dir }}/{{ item }}"
  with_items:
    - letsencrypt-prod-clusterissuer.yaml
    - letsencrypt-staging-clusterissuer.yaml
