---
configInline:
  peers:
  - peer-address: "{{ metallb_peer_address }}"
    peer-asn: {{ metallb_peer_asn }}
    my-asn: {{ metallb_peer_asn }}
  address-pools:
  - name: default
    protocol: bgp
    addresses:
    - "{{ metallb_peer_address }}/24"
